#!/usr/bin/env node
// scripts/gen-version.mjs
// 单一可信源:root package.json "version"。
// 生成 apps/web/src/lib/version.ts(build-time 写入静态常量,适配静态导出),
// 并把 apps/desktop/src-tauri/tauri.conf.json 的 version 字段同步过来。
//
// Why:之前版本号散落在 4 处(package.json / tauri.conf.json / page.tsx 硬编码 /
// app-menu 无),手动同步必然漂移。这里收敛到一个源头 —— root package.json。
// prebuild / predev 钩子触发,所以每次 build / dev 都自动刷新,无需新增依赖。
//
// No file deps — only node:fs + node:path。Node 18+。

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const PKG = resolve(ROOT, 'package.json')
const VERSION_TS = resolve(ROOT, 'apps/web/src/lib/version.ts')
const TAURI_CONF = resolve(ROOT, 'apps/desktop/src-tauri/tauri.conf.json')

// 1) 读取单一可信源。
const pkg = JSON.parse(readFileSync(PKG, 'utf8'))
const version = pkg.version
if (!version || typeof version !== 'string') {
  console.error(`gen-version: root package.json has no valid "version" string`)
  process.exit(1)
}

// 2) 写 apps/web/src/lib/version.ts(静态常量,静态导出可直接 import)。
const tsContent =
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit; source of truth is root package.json "version".\n` +
  `export const VERSION = '${version}'\n`
if (!existsSync(VERSION_TS) || readFileSync(VERSION_TS, 'utf8') !== tsContent) {
  writeFileSync(VERSION_TS, tsContent)
}

// 3) 同步 tauri.conf.json 的 version(保留原 JSON 格式;仅改 version 字段)。
const raw = readFileSync(TAURI_CONF, 'utf8')
const trailingNewline = raw.endsWith('\n')
const conf = JSON.parse(raw)
if (conf.version !== version) {
  conf.version = version
  // Tauri 配置用 2-space 缩进;保留尾部换行。
  const next = JSON.stringify(conf, null, 2) + (trailingNewline ? '\n' : '')
  writeFileSync(TAURI_CONF, next)
}

// 4) 日志。
console.log(`gen-version: ${version} → apps/web/src/lib/version.ts, tauri.conf.json`)
